### ISSUE TITLE
Create a "Lost at Sea" game module

### ISSUE THREAD

**Issue by cjqian** [PAIR-code/llm-mediation-experiments#22]
Currently, this is the only game in the platform. We should consider splitting up the variations as tasks. From the tech doc: 

> It would be nice that once the module is created, it loops over all the items (in a randomized order) (6) + 8) to be discussed which way we can devise to organize module repetitions and loops)
> * Make the automation of experiment creation easier. 
> * Make it possible to create a set of items that will be used (and a button to do random assignment, and ordering).

**Comment by vivtsai** [comment]
Current scope of this is to enable one-click creation of Lost at Sea stages (i.e., randomly generate item pairs and use to populate surveys and chat as they are created).

We can open up a follow-up FR to enable customization (e.g., specifying number of pairs, allowing re-randomization) - this requires more effort because it involves updating multiple stages, and we don't currently have a bit to track what module a stage is part of.
