### ISSUE TITLE
Update backend function to reset `readyToEndChat` after incrementing the discussion index

### ISSUE THREAD

**Issue by vivtsai** [PAIR-code/llm-mediation-experiments#55]
The function `publishParticipantReadyToEndChat` in `functions/src/triggers/chats.triggers.ts` automatically increments the discussion index when all participants are ready to move forward, but does not reset participants' `readyToEndChat` field.

Not sure how this is currently working in the Angular app, but I think it would make sense to set `readyToEndChat` to false here if the discussion index is not at the final stage.

Speaking of, the discussion index increments past the length of discussions—so maybe prevent incrementation in the "final stage" case too.

**Comment by vivtsai** [comment]
@TiboX2021 what do you think?

**Comment by TiboX2021** [comment]
I used `currentRatingIndex` being `>=` to ratings count as a way to identify that the chat ended from the frontend side (which is aware of the total ratings count). I found it more convenient to use rather than an additional flag (for auto redirect to the next stage once the chat stage ends, as in the first webapp versions this would be automatic, without a "Next stage" button). In particular, the `currentRatingIndex` is only used for internal logic, it is not relevant to the experiment once the chat has ended, so I don't think it is that important if is out of bounds in the end.

**Comment by TiboX2021** [comment]
About `publishParticipantReadyToEndChat`: I wanted to limit document reads, so I did not add backend logic in this trigger function to read the participant private IDs in order to flip their `readyToEndChat` values from here.

I have no experience with firebase costs, so I do not know if it is really necessary to avoid this. However, I think that flipping these values from the backend is better in terms of logic because it is supposed to be an automated action, and it avoids infinite loop bugs because of race conditions (when there are automated flips both in the backend and the frontend. If we keep the frontend manual, there will be no such bugs, which have happened in the angular webapp).

**Comment by vivtsai** [comment]
Hi! Okay, I agree with you on the currentRatingIndex (out of bounds at the end is okay).

For flipping readyToEndChat - the code Crystal merged yesterday edits the chat trigger function to reset values when incrementing discussion index: https://github.com/PAIR-code/llm-mediation-experiments/blob/main/functions/src/triggers/chats.triggers.ts#L47

However, this actually only updates the bit under publicData, and not the private ChatAnswer bit under `$PARTICIPANT_ID/chats/$CHAT-ID`. I wasn't sure if there was a best practice for doing the latter (e.g., instead of manually writing both bits, calling the same "update readyToEndChat" function that the frontend calls). Is this something you'd be able to help with... or should I just query for all the participant private IDs in this function?

**Comment by TiboX2021** [comment]
The public data should not be written to, it is only a copy of data stored elsewhere, being copied by firestore trigger functions. The easiest solution would indeed be to query the participant ID in the `readyToEndChat` function.

The idea behind this is that because we do not authenticate participants in firebase, the documents they are supposed to be able to write to are not protected. Basically, if you know the document URI, you can write to it.

In order to avoid anyone writing anything for any participant, the actual source of truth must be the private `$PARTICIPANT_ID/chats/$CHAT-ID`. The public bit is readable by every participant, thus cannot be written to without authentication. In particular, the `readyToEndChat` bit is directly copied from the private bit by trigger functions, so you must always edit the private one.

**Comment by vivtsai** [comment]
Thanks for clarifying! Do you have bandwidth to pick this bug fix up, or shall I?

**Comment by TiboX2021** [comment]
I can fix this, I'll push it directly on main
